### ISSUE TITLE
Enhancement for specifying different output path

### ISSUE THREAD

**Issue by Malzmeier** [ElektroStudios/Dolphin_Emulator_RVZ_ISO_GameCube_Wii_Conversion_Scripts#2]
This looks great, but I'm missing an option to specify a different output path for the converted files.
This would make the script even more versatile.

I don't have much knowledge in coding, but I guess it it could be implemented without much effort.

**Comment by ElektroStudios** [comment]
Hello! Thanks for providing your suggestions.

I've added a new setting with name `$outputDirectoryPath` in the "**Script Settings**" block of the script files, to let the user define the output directory path for conversion and extraction operations:

![WinSnap 01](https://github.com/ElektroStudios/Dolphin_Emulator_RVZ_ISO_GameCube_Wii_Conversion_Scripts/assets/13082613/0b7a7c1b-57bb-4e22-a6b1-6dd522fbaff6)

I've also added it to the Batch-script files.

Please download and use the [version 1.2](https://github.com/ElektroStudios/Dolphin_Emulator_RVZ_ISO_GameCube_Wii_Conversion_Scripts/releases/tag/v1.2) of the script files.

If you still have any doubts related to this, feel free to reopen this issue.

Best regards!.
